### PR TITLE
Replacing emojis with replacement character

### PR DESCRIPTION
**Pull request by elias-ba**
We, now, use the replacement character (U+FFFD) to replace all the emojis.
We also allow to chose a specific replacement character if needed and pass it as parameter to the function.
This refactored, to fix potential security vulnerability in replacing with empty string

### CODE REVIEW

**Comment by elias-ba** [comment]
I am a little worried by the idea of ​​alerting to the potential security problems that a given parameter can present. It even seems to me to be a security flaw in the function.

**Comment by taylordowns2000** [comment]
Key to remember that they can create their own vulnerabilities however they'd like; and they can also write their own string.replace function.

IMO, the thing to do if we're gonna give them a helper function here is to make sure they're aware of how a certain type of use could cause vulnerabilities.

In the current clients case, they're not creating any vulnerability because this is before it hits the Salesforce API. For other kinds of usage, they could (if they really try, and do so ignoring our "don't do that" warnings) create vulnerabilities in their own systems. They cannot, however, create vulnerabilities in the host system (a platform or microservice deployment)

React provided "dangerouslySetInnerHtml" as an attribute! In my mind it's kinda like that.

Thoughts? Or propose another way forward?

**Comment by elias-ba** [comment]
Great ! Thanks @taylordowns2000 for your explanations. I find them very relevant and I do agree. Have added it to the function.

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
1. missing the hyperlink
2. on line `479` there's an extra article in the docs headline
3. `replacementChar` should be `replacementChars` or `replacementString`, because it looks like it can take any string, not just a single character.
4. why do you use `unescape` in line 309?

**Comment by elias-ba** [comment]
> 1. missing the hyperlink
> 2. on line `479` there's an extra article in the docs headline
> 3. `replacementChar` should be `replacementChars` or `replacementString`, because it looks like it can take any string, not just a single character.
> 4. why do you use `unescape` in line 309?

Great, thanks.
1. Is the hyperlink this one : http://www.unicode.org/reports/tr36/#Deletion_of_Noncharacters ?
4. Sorry, I missed removing unescape. Removed it

**Comment by taylordowns2000** [comment]
It is!

**Pull request merged**
